version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:20.04
    steps:
      - checkout:
      - run: echo "Hello, world!"
      - add_ssh_keys:
          fingerprints:
            - "4c:ff:a5:f0:f3:8b:6e:51:83:79:ef:b0:49:e2:31:56"
      - run: sh ./deploy.sh
